name: Publish

on:
  workflow_dispatch:
  push: 
    branches:
    - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkoput@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore
        run: dotnet restore ./TestAngularJS.sln
        
      - name: Build
        run: dotnet build ./TestAngularJS.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./TestAngularJS.sln --configuration Release --no-build
